# Generated by Django 5.1.6 on 2025-02-25 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedspaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=128)),
                ("address", models.CharField(max_length=128)),
                ("phone_number", models.CharField(max_length=128)),
                ("email_address", models.EmailField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration", models.IntegerField()),
                (
                    "medspa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="services",
                        to="medspa.medspamodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppointmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("start_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "scheduled"),
                            ("COMPLETED", "completed"),
                            ("CANCELED", "canceled"),
                        ],
                        default="SCHEDULED",
                        max_length=24,
                    ),
                ),
                (
                    "medspa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="appointments",
                        to="medspa.medspamodel",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        related_name="appointments", to="medspa.servicemodel"
                    ),
                ),
            ],
        ),
    ]
